export type Article = {
  slug:string; title:string; excerpt:string; category:string; date:string;
  image:string; body:string[]; sources:string[]; readTime?:string; featured?:boolean;
};

export const articles: Article[] = [
  {slug:"por-que-el-cielo-es-azul",title:"¿Por qué el cielo es azul?",excerpt:"Una de las preguntas más sencillas tiene una explicación física sorprendente.",category:"Ciencia",date:"2026-09-24",readTime:"4 min",featured:true,image:"https://images.unsplash.com/photo-1534088568595-a066f410bcda?auto=format&fit=crop&w=1600&q=85",body:["La luz del Sol parece blanca, pero está formada por diferentes longitudes de onda. Cuando entra en la atmósfera, las moléculas del aire dispersan esas ondas de manera diferente.","Las longitudes de onda más cortas, asociadas al azul y al violeta, se dispersan con mayor facilidad que las más largas. Nuestros ojos son más sensibles al azul y parte de la luz violeta es absorbida en la atmósfera, por eso percibimos principalmente el cielo azul.","Al amanecer y al atardecer la luz atraviesa una mayor cantidad de atmósfera. La dispersión elimina gran parte de los tonos azules del camino directo y permite que los rojos y naranjas dominen el paisaje."],sources:["NASA Science","NOAA"]},
  {slug:"un-dia-en-venus",title:"En Venus, un día dura más que un año",excerpt:"La rotación y la órbita de Venus producen una de las peculiaridades más llamativas del Sistema Solar.",category:"Espacio",date:"2026-09-23",readTime:"3 min",image:"https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=1600&q=85",body:["Venus tarda alrededor de 243 días terrestres en completar una rotación sobre su eje, mientras que tarda aproximadamente 225 días terrestres en completar una órbita alrededor del Sol.","Eso significa que su periodo de rotación sideral es más largo que su año. Además, Venus gira en sentido contrario al de la mayoría de los planetas.","Es un buen ejemplo de cómo una palabra tan cotidiana como 'día' puede esconder varias definiciones astronómicas."],sources:["NASA Solar System Exploration"]},
  {slug:"por-que-sonamos",title:"¿Por qué soñamos?",excerpt:"Los sueños siguen siendo un área activa de investigación científica.",category:"Cuerpo y mente",date:"2026-09-22",readTime:"5 min",image:"https://images.unsplash.com/photo-1499209974431-9dddcece7f88?auto=format&fit=crop&w=1600&q=85",body:["Los sueños aparecen durante diferentes fases del sueño y son especialmente frecuentes durante el sueño REM, aunque también pueden existir experiencias oníricas fuera de esa fase.","La ciencia todavía no tiene una explicación única y definitiva de por qué soñamos. Se han propuesto funciones relacionadas con memoria, procesamiento emocional y simulación de experiencias.","Lo importante es separar las hipótesis científicas de las interpretaciones populares: que un sueño tenga un significado simbólico concreto no es una conclusión científica general."],sources:["NIH / National Institute of Neurological Disorders and Stroke"]},
  {slug:"que-pasaria-si-desapareciera-la-luna",title:"¿Qué pasaría si la Luna desapareciera?",excerpt:"Una hipótesis imposible que permite entender cuánto influye nuestro satélite en la Tierra.",category:"¿Qué pasaría si...?",date:"2026-09-21",readTime:"6 min",image:"https://images.unsplash.com/photo-1532693322450-2cb5c511067d?auto=format&fit=crop&w=1600&q=85",body:["La Luna influye en las mareas terrestres y estabiliza parcialmente la inclinación del eje de la Tierra. Su desaparición no provocaría que el planeta se detuviera, pero sí cambiaría el sistema de mareas y, a largo plazo, la dinámica de la inclinación terrestre.","Las mareas no desaparecerían por completo porque el Sol también produce mareas, aunque serían diferentes. Los ecosistemas costeros que dependen de los ciclos actuales tendrían que adaptarse.","Es una hipótesis útil porque muestra que un objeto que parece pequeño comparado con la Tierra puede tener efectos planetarios importantes."],sources:["NASA","NOAA"]},
  {slug:"animal-que-puede-regenerarse",title:"El animal capaz de regenerar partes de su cuerpo",excerpt:"Algunas especies han desarrollado capacidades de regeneración que todavía sorprenden a los investigadores.",category:"Animales",date:"2026-09-20",readTime:"5 min",image:"https://images.unsplash.com/photo-1544550285-f813152fb2fd?auto=format&fit=crop&w=1600&q=85",body:["La regeneración aparece en distintos animales y puede ir desde reparar tejidos hasta reconstruir estructuras complejas. Las salamandras, por ejemplo, son un modelo clásico de investigación regenerativa.","Estudiar estos procesos ayuda a comprender cómo las células reciben señales para crecer, diferenciarse y organizar tejidos.","La regeneración animal no significa que los humanos puedan reproducir esas capacidades; la investigación intenta comprender los mecanismos biológicos que las hacen posibles."],sources:["National Institutes of Health","Nature Education"]},
  {slug:"por-que-el-oceano-es-azul",title:"¿Por qué el océano parece azul?",excerpt:"El color del mar depende de cómo la luz interactúa con el agua y con lo que contiene.",category:"Planeta",date:"2026-09-19",readTime:"4 min",image:"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=85",body:["El agua absorbe algunas longitudes de onda de la luz con mayor eficacia que otras. Los tonos rojos y amarillos se atenúan antes al penetrar en el agua, mientras que parte de la luz azul puede regresar hacia nuestros ojos.","El color real también depende de sedimentos, organismos microscópicos, profundidad, cielo y condiciones atmosféricas.","Por eso dos zonas de océano pueden mostrar tonos muy diferentes sin que exista una sola causa."],sources:["NOAA Ocean Service"]}
];

export const quickFacts = [
  "Los pulpos tienen tres corazones.",
  "Venus tarda más en girar sobre su eje que en completar una órbita alrededor del Sol.",
  "Un rayo puede calentar el aire a temperaturas enormes durante un instante extremadamente corto.",
  "Los tiburones existen desde mucho antes que los dinosaurios modernos.",
  "La Antártida es el continente más frío, seco y ventoso de la Tierra."
];

export const whatIf = [
  {title:"¿Qué pasaría si la Tierra dejara de girar durante 5 segundos?",category:"Planeta",image:"https://images.unsplash.com/photo-1614730321146-b6fa6a46bcb4?auto=format&fit=crop&w=1000&q=85"},
  {title:"¿Qué pasaría si pudiéramos viajar a la velocidad de la luz?",category:"Espacio",image:"https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=1000&q=85"},
  {title:"¿Qué pasaría si la Tierra tuviera dos lunas?",category:"Espacio",image:"https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3?auto=format&fit=crop&w=1000&q=85"}
];

export const videoTopics = [
  {title:"El universo explicado",query:"NASA universe explained",image:"https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=1000&q=85"},
  {title:"Cómo funciona el cerebro",query:"brain science explained",image:"https://images.unsplash.com/photo-1559757175-0eb30cd8c063?auto=format&fit=crop&w=1000&q=85"},
  {title:"Los lugares más extremos de la Tierra",query:"extreme places Earth documentary",image:"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1000&q=85"}
];
